### PR TITLE
fix(preview-middleware): loading i18n bundle for CAP projects

### LINKED ISSUE #3721: BUG - Unable to load i18n bundle when started with CDS
### Description
UI frontend is unable to load the i18n bundles when loaded via a CAP project.

[i18n property function](https://github.com/SAP/open-ux-tools/blob/master/packages/preview-middleware/src/base/config.ts#L328) is loaded with a path of `.` instead of `./app/<project-name>`.

```bash
}
info fiori-tools-proxy Using UI5 version 1.140.0 based on manifest.json
info fiori-tools-proxy Starting fiori-tools-proxy using following configuration:
info fiori-tools-proxy proxy: 'undefined'
info fiori-tools-proxy ignoreCertErrors: 'false'
info fiori-tools-proxy backend: undefined
info fiori-tools-proxy ui5: [{"path":"/resources","url":"https://sapui5.hana.ondemand.com","version":"1.140.0"},{"path":"/test-resources","url":"https://sapui5.hana.ondemand.com","version":"1.140.0"}]
info fiori-tools-proxy debug: 'false'
info fiori-tools-appreload Livereload middleware started for port 35729 and path /Users/Downloads/cap-app/app/translation-ui/webapp
warn fiori-tools-preview Failed to load i18n properties bundle
warn fiori-tools-preview Failed to load i18n properties bundle
```

This is not an issue when deployed, only impacts SAPUI5 apps when rendered locally.

### Steps to Reproduce
1. Generate a CAP project;
```bash
cds init managedAppCAPProject && cd  managedAppCAPProject && npm install && cds add tiny-sample && cds add hana && cds add mta && cds add xsuaa && cds add connectivity && cds add destination && cds add html5-repo && cds build --for hana && cp gen/db/package.json db && npm i
```
3. Append a SAPUI5 UI app using SAP Fiori tools generator
4. Start the server using `npm run start`

### Expected results

i18n bundle is loaded

### Actual results

i18n fails to load since the project path is `.` and the UI app is not found in that path.

### Screenshots
If applicable, add screenshots to help explain the problem.

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

### PR DESCRIPTION
**Pull request by heimwege**
fixes #3721

Adjust preview middleware to use absolute instead of relative local path. For additional flp.apps absolute and relative paths are supported

Also fixes an issue that instantiating project-access with `createProjectAccess('.')` returns ALL projects in `.` (and subdirectories). preview-middleware uses the first found app and might return wrong i18n 🙈

### CODE REVIEW

File: packages/preview-middleware/src/base/config.ts [hunk 1]
```diff
@@ -336,8 +346,9 @@ async function getI18nTextFromProperty(
     }
     const projectAccess = await createProjectAccess(projectRoot);
     const applicationIds = projectAccess.getApplicationIds();
+    const applicationId = applicationIds.find((id) => id === appId) ?? applicationIds[0];
     try {
-        const bundle = (await projectAccess.getApplication(applicationIds[0]).getI18nBundles())['sap.app'];
+        const bundle = (await projectAccess.getApplication(applicationId).getI18nBundles())['sap.app'];
```
Comment (heimwege) [inline packages/preview-middleware/src/base/config.ts]: Can we simply use appId here and skip calling getApplicationIds from project access?

Comment (Klaus-Keller) [reply packages/preview-middleware/src/base/config.ts]: @heimwege 
if you have the path to the app, you can call `createApplicationAccess()` directly:
https://github.com/SAP/open-ux-tools/blob/a658553551950d005d4c94b215668ad38711f3de/packages/project-access/src/project/access.ts#L384-L387

Comment (heimwege) [reply packages/preview-middleware/src/base/config.ts]: adjusted

**Review by Klaus-Keller — APPROVED** [review]
Re-approve

**Review by Klaus-Keller — APPROVED** [review]
Re-approve

**Review by Klaus-Keller — APPROVED** [review]
re-approve
